[package]
name = "chip-8-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
chip-8-core = { path = "../core" }
clap = { version = "4.5", features = ["derive"] }
sdl2 = { version = "0.37.0" }